name: PCFly
main: Angel\PCFly\Main
api: 3.0.0
version: 3.0.0
author: Angel and fixed by Leo
commands:
  plotsfly:
    description: "Fly in survival mode with restrictions"
permissions:
  fly.command:
    default: true
